
xcorr <- ccf(transdataframe$Trader, prices$Apple, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Trader, prices$Twitter, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Trader, prices$Facebook, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Trader, prices$Chipotle, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Trader, prices$Schroders, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Trader, prices$HSBC, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Trader, prices$Goldman, lag.max=NULL, type=c("correlation"), plot=TRUE)

xcorr <- ccf(transdataframe$Obama, prices$Apple, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Obama, prices$Twitter, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Obama, prices$Facebook, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Obama, prices$Chipotle, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Obama, prices$Schroders, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Obama, prices$HSBC, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Obama, prices$Goldman, lag.max=NULL, type=c("correlation"), plot=TRUE)

xcorr <- ccf(transdataframe$Oil, prices$Apple, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Oil, prices$Twitter, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Oil, prices$Facebook, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Oil, prices$Chipotle, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Oil, prices$Schroders, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Oil, prices$HSBC, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Oil, prices$Goldman, lag.max=NULL, type=c("correlation"), plot=TRUE)

xcorr <- ccf(transdataframe$Interest, prices$Apple, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Interest, prices$Twitter, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Interest, prices$Facebook, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Interest, prices$Chipotle, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Interest, prices$Schroders, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Interest, prices$HSBC, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Interest, prices$Goldman, lag.max=NULL, type=c("correlation"), plot=TRUE)

xcorr <- ccf(transdataframe$Baltimore, prices$Apple, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Baltimore, prices$Twitter, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Baltimore, prices$Facebook, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Baltimore, prices$Chipotle, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Baltimore, prices$Schroders, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Baltimore, prices$HSBC, lag.max=NULL, type=c("correlation"), plot=TRUE)
xcorr <- ccf(transdataframe$Baltimore, prices$Goldman, lag.max=NULL, type=c("correlation"), plot=TRUE)
